### ISSUE TITLE
GPU memory requirement?

### ISSUE THREAD

**Issue by 18445864529** [krystalan/ClidSum#1]
I noticed the default bsz is 4. I got OOM at this number so I reduced it all the way to 1 but still got the OOM error. I was using a single GPU with 16G memory. May I ask how much memory is needed to run with bsz 4? It doesn't make sense that 16G can't even run at bsz 1, maybe I'm missing something?

**Comment by krystalan** [comment]
Hi, thanks for your interest. We run batch size 4 on 32G memory GPU (V100). I guess batch size 1 needs about 20G memory but I haven't tried. The average length of XMediaSum is over 1024 token, making it needs a large memory. If you only have 16G GPUs, I suggest you do research on XSAMSum whose average length is much less than XMediaSum, and then, you can set the max_input_len to 512 or even 256.

**Comment by 18445864529** [comment]
Thanks for your explanation. I used a different machine with 24G GPU memory and succeeded in running bsz of 4. The current memory usage is about 21G.
