### ISSUE TITLE
Any plan for releasing the 2nd stage pre-training code as well?

### ISSUE THREAD

**Issue by 18445864529** [krystalan/ClidSum#3]

**Comment by krystalan** [comment]
The pre-training code is very similar to `run_XMediaSum40k.py`. 
Just (1) replace the `mDialBART` with `mBART-50`; (2) add a special token `[SUM]` to original token embeddings like this:
```
self.tokenizer = MBart50TokenizerFast.from_pretrained(self.args.model_path, src_lang=self.src_lang, tgt_lang=self.tgt_lang) 
additional_tokens = ['[summarize]']
self.tokenizer.add_tokens(additional_tokens)
self.model = MBartForConditionalGeneration.from_pretrained(self.args.model_path)
self.model.resize_token_embeddings(len(self.tokenizer))
```
and (3) train the model by four pre-training tasks.

**Comment by 18445864529** [comment]
Thanks for the reply. Is it possible to attach the code of 4 pre-training tasks? I think it is the core of the 2nd stage pretraining in mdialbart.

**Comment by krystalan** [comment]
Well, we first process the training samples of four pre-training tasks and then directly use the samples to further pre-train `mBART-50`.

The codes for processing pre-training samples are not saved, and I think these codes are not difficult to write. I can provide the processed samples of four pre-training tasks, just leave your email.

And, the code for the second pre-training stage is just like `run_XMediaSum40k.py` which we discussed before.

**Comment by 18445864529** [comment]
I see. Please send to qq787204126@gmail.com. Thanks.
